allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@bigcommerce/big-design-icons@3.0.0'
  - '@bigcommerce/big-design-theme@3.0.0'
  - '@bigcommerce/big-design@5.0.0'
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
patchedDependencies:
  '@bigcommerce/big-design': patches/@bigcommerce__big-design+modal-removechild-detached-node.patch
peerDependencyRules:
  allowedVersions:
    "@bigcommerce/big-design>react": "19"
    "@bigcommerce/big-design>react-dom": "19"
    "@bigcommerce/big-design-theme>react": "19"
    "@bigcommerce/big-design-theme>react-dom": "19"
    "@bigcommerce/big-design-icons>react": "19"
    "@bigcommerce/big-design-icons>react-dom": "19"
