allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@bigcommerce/big-design-icons@3.0.0'
  - '@bigcommerce/big-design-theme@3.0.0'
  - '@bigcommerce/big-design@5.0.0'
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
patchedDependencies:
  '@bigcommerce/big-design': patches/@bigcommerce__big-design+modal-removechild-detached-node.patch
