-- One row per store. extension_id is BigCommerce's own opaque id, not
-- generated by this app. Split into its own migration for the same reason as
-- the Postgres driver's 0002: the App Extension feature landed after the
-- initial schema, and an already-provisioned database needs an incremental
-- step rather than an edit to 0001.
CREATE TABLE store_extensions (
  store_hash TEXT PRIMARY KEY REFERENCES stores (store_hash) ON DELETE CASCADE,
  extension_id TEXT NOT NULL
);
