import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import { ActionAlertsManager } from "@/components/ui/action-alerts";
import "./globals.css";

const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sourceSans3.className}>
      <body>
        {children}
        <ActionAlertsManager />
      </body>
    </html>
  );
}
