-- One row per store. extension_id is BigCommerce's own opaque id, not
-- generated by this app.
CREATE TABLE store_extensions (
  store_hash TEXT PRIMARY KEY REFERENCES stores (store_hash) ON DELETE CASCADE,
  extension_id TEXT NOT NULL
);
